// Root layout for the app. This file sets up global fonts, metadata and the
// top-level HTML structure used by Next.js' App Router.
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Configure Google fonts via Next's built-in `next/font` helper. These create
// CSS variables we inject into the `<body>` so the rest of the app can use
// the selected font families without additional CSS imports at component level.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Page metadata used by Next.js. Edit title/description for SEO and previews.
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout: wraps all pages. `children` is the content for each page route.
// We add the font CSS variable class names to the `<body>` so Tailwind or plain
// CSS can reference those variables for font-family fallbacks.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Link fallback fonts from Google Fonts. This is optional because Next's
            font helper above also provides fonts, but keeping this ensures the
            fonts load consistently in environments where the helper may differ. */}
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Space+Grotesk:wght@700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
